version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    environment:
      - JDBC_URI=jdbc:postgresql://ep-proud-queen-a2olf34j.eu-central-1.pg.koyeb.app/koyebdb?user=koyeb-adm&password=Qpm5s6DvJkhj
    ports:
      - "8000:8000"