version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    environment:
      - JDBC_URI=jdbc:postgresql://ep-summer-moon-a2hy2sb4.eu-central-1.pg.koyeb.app/koyebdb?user=koyeb-adm&password=rKiT2n3xgGoU
    ports:
      - "8000:8000"